global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'pd'
    static_configs:
      - targets: ['pd:2379']

  - job_name: 'tikv'
    static_configs:
      - targets: ['tikv:20160']

  - job_name: 'tidb'
    static_configs:
      - targets: ['tidb:10080']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']

  - job_name: 'zookeeper'
    static_configs:
      - targets: ['zookeeper:8080']
