
services:
  pd:
    image: pingcap/pd:v6.5.0
    container_name: pd
    ports:
      - "2379:2379"
      - "2380:2380"
    command:
      - "--name=pd"
      - "--data-dir=/pd/data"
      - "--client-urls=http://0.0.0.0:2379"
      - "--peer-urls=http://0.0.0.0:2380"
      - "--initial-cluster=pd=http://pd:2380"
    volumes:
      - pd-data:/pd/data

  tikv:
    image: pingcap/tikv:v6.5.0
    container_name: tikv
    depends_on:
      - pd
    ports:
      - "20160:20160"
    command:
      - "--pd=pd:2379"
      - "--data-dir=/tikv/data"
    volumes:
      - tikv-data:/tikv/data

  tidb:
    image: pingcap/tidb:v6.5.0
    container_name: tidb
    depends_on:
      - pd
      - tikv
    ports:
      - "4000:4000"
      - "18080:10080"  # Dashboard
    command:
      - "--store=tikv"
      - "--path=pd:2379"

  zookeeper:
    image: zookeeper:3.8.1
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  kafka:
    image: bitnami/kafka:3.5.1
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.0.3
    container_name: grafana
    ports:
      - "3000:3000"

volumes:
  pd-data:
  tikv-data:
