
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: home-test-zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    image: wurstmeister/kafka
    container_name: home-test-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    restart: unless-stopped

  tidb:
    image: pingcap/tidb:latest
    container_name: home-test-tidb
    ports:
      - "4001:4000"
      - "10080:10080"
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: home-test-backend
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      DATABASE_HOST: tidb
      DATABASE_PORT: 4000
      KAFKA_BROKER: kafka:9092
    depends_on:
      - tidb
      - kafka
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: home-test-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
